name: Python application

on:
  push:
    branches: [ master, smirnov/Artifact ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create enviroment
      run: |
        mkdir -p path/to/artifact
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pydocstyle pytest setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: Check docstyle
      run: |
        pydocstyle city_builder/Sources/Utils.py
    - name: Pytest
      run: |
        pytest city_builder/Sources/Tests.py
    - name: Create wheel
      run: |
        python setup.py bdist_wheel
        cp dist/city_builder-1.0-py3-none-any.whl path/to/artifact/
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifact/city_builder-1.0-py3-none-any.whl   
#     - name: Test with pytest
#       run: |
#         pytest
